#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall -q polybar

# on-boot programs
$HOME/.screen_layout/external.sh
xset s off 
xset s noblank
xset -dpms
nitrogen --restore &
picom -m 1 -i 1 &
xsetroot -cursor_name left_ptr

# monitor and polybar settings
bspc wm --reorder-monitors DP-1 HDMI-0
bspc monitor DP-1 -d 1 3 5
bspc monitor HDMI-0 -d 2 4 6
polybar main &
polybar secondary &

# colors
bspc config normal_border_color     '#575268'
bspc config active_border_color     '#d9e0ee'
bspc config focused_border_color    '#d9e0ee'
bspc config presel_feedback_color   '#abe9b3'

# Window Config
bspc config border_width            2
bspc config window_gap              8
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config top_monocle_padding     8

