#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# on-boot programs
xset s off 
xset s noblank
xset -dpms
nitrogen --restore &
picom -m 1 -i 1 &
xsetroot -cursor_name left_ptr

# colors
bspc config normal_border_color     '#575268'
bspc config active_border_color     '#f5c2e7'
bspc config focused_border_color    '#f5c2e7'
bspc config presel_feedback_color   '#f5c2e7'

# Window Config
bspc config border_width            2
bspc config window_gap              8
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
